sudo: required
services:
    - docker

before_install:
    - docker build -t mattshine/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true mattshine/react-test npm test

after_success:
    - docker build -t mattshine/multi-client ./client
    - docker build -t mattshine/multi-nginx ./nginx
    - docker build -t mattshine/multi-server ./server
    - docker build -t mattshine/multi-worker ./worker
    # login to docker hub, take those images and push them to docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push mattshine/multi-client
    - docker push mattshine/multi-nginx
    - docker push mattshine/multi-server
    - docker push mattshine/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-165561119974
    bucket_path: multi-docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY